[ether]
addr = "ws://host.docker.internal:8546"
name = "ether"
contract_address = "0xD3880ea40670eD51C3e3C0ea089fDbDc9e3FBBb4"
key_path = "account.key"
password = "password"
min_confirm = 1
timeout_height = 10

[[services]]
id = "0xBd0F020738f9ecbF447B040E211D2E10bF2264fe"
name = "transfer"
abi = "transfer.abi"